### ISSUE TITLE
Improve example to use hasNextPage for connection

### ISSUE THREAD

**Issue by jpshelley** [apollographql/react-docs#101]
This is more of a question than an issue:

The relay cursor page (https://github.com/apollostack/react-docs/blob/master/source/pagination.md) includes the mention of the `hasNextPage` variable which is returned from the server.

**_tldr: (Logic resides in Apollo vs custom React.Component)_**
Does it make sense for apollo to handle whether the query should perform a `fetchMore` based on that variable? Or should it be up to the individual React.Component to execute `fetchMore()` by checking the `hasNextPage` first?

**Comment by stubailo** [comment]
Right now, we're totally unopinionated about pagination, so I think you could add some logic to check it. It should be encapsulated in the `props` method of the container I think.

I feel like the component would need to check it anyway though, because you probably want to display the end of a list differently in the UI than a midpoint (perhaps by having a "load more" button, or something).

**Comment by stubailo** [comment]
I think it would be cool to have a helper library for Apollo to work with connections, though, since a lot of people would like to use those for pagination. We don't use that pagination model but if you do it would be great to have some ideas about how we could better support it!

**Comment by jpshelley** [comment]
Totally, that makes sense. A helper library would be nice. Unsure of how it would look as I'm just getting started with it but open to provide input once we start learning more of what works and what doesn't.

**Comment by stubailo** [comment]
Thanks a lot, would really appreciate that!

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
