### ISSUE TITLE
Split propTypes into a new article

### ISSUE THREAD

**Issue by stubailo** [apollographql/react-docs#118]
We have some stuff about that here, in the context of fragments: http://dev.apollodata.com/react/fragments.html#creating-fragments

But this approach works for queries as well! Moreover, I think propTypes are going to be a very common question people run into and is a pretty fundamental aspect of React. I think we should move this stuff into a new recipe page about propTypes that we can link to.

Related: https://github.com/apollostack/react-apollo/issues/333

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
