### ISSUE TITLE
Clarify server-side rendering docs.

### ISSUE THREAD

**Issue by jnwng** [apollographql/react-docs#123]
i got hung up on [this change](https://github.com/apollostack/react-docs/commit/2ae971b4e5b3d23ff70574447030aee37e44097b#diff-e65085a675fc082c408f1708267d9b28L23) in the server-side rendering docs - when setting `initialState` in the ApolloClient during [store rehydration](https://github.com/apollostack/react-docs/blob/2ae971b4e5b3d23ff70574447030aee37e44097b/source/server-side-rendering.md#store-rehydration) it expected the `reduxRootKey` as one of the top-level keys on the data being passed to it, e.g., 
```
const client = new ApolloClient({
  initialState: {[reduxRootKey]: window.__APOLLO_STATE__}
});
```
however, earlier in this file the example given is just
```
const client = new ApolloClient({
  initialState: window.__APOLLO_STATE__
});
``` 
(apologies for not being able to link where this happens, for some reason i can't see the source markdown in github, and only see their rendered preview).

i think it'd be useful to be clear about using `reduxRootKey` throughout, and either set it in the example where we're putting the stringified data into the HTML, or when the client itself is being initialized.

/cc @tmeasday as this change relates to some of the recent docs changes you made.

**Comment by stubailo** [comment]
Yeah this is inconsistent.

> (apologies for not being able to link where this happens, for some reason i can't see the source markdown in github, and only see their rendered preview).

Yeah this is a pretty big flaw in GitHub markdown stuff haha - no way to view source.

@tmeasday can you figure out which is the right one and make sure it's correct in all the docs? I hope it's the one without `reduxRootKey`.

**Comment by tmeasday** [comment]
Yeah it's a bit of a mess.

It seems like AC expects you to set `initialState` to something with the `reduxRootKey`. The reason the docs are inconsistent is that at one point we just serialized `store.getState()`, but now you need to just pull out the `apollo.data` part of the store, as you can't pass in queries.

@jnwng if you see points where the docs are wrong can you send a PR with a fix? That'd be appreciated.

Would it make sense for `new ApolloClient` to take an `initialState` option which is consistent with the output of `client.getInitialState()` (https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L558)? (at the moment `initialState` wants a `reduxRootKey` which isn't output by `getInitialState()`)? cc @helfer

**Comment by helfer** [comment]
@tmeasday yes, that would make perfect sense. In fact, I've just opened an issue about that on ApolloClient: https://github.com/apollostack/apollo-client/issues/1033

**Comment by voidale** [comment]
initialState doesn't even seems to work, I had to use redux initial state to make it work

**Comment by DimitryDushkin** [comment]
@voidale try snippet from https://github.com/apollostack/react-docs/pull/134 Works for me.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
