### ISSUE TITLE
Use `reduxRootSelector` instead of `reduxRootKey`

### ISSUE THREAD

**Issue by choonkending** [apollographql/react-docs#143]
# Problem

Given that I get the warning 
> reduxRootKey" option is deprecated and might be removed in the upcoming versions, please use the "reduxRootSelector" instead.

We should update the docs to specify `reduxRootSelector` instead of `reduxRootKey`, unless there are complications.

Happy to edit and contribute if it's a straight forward change!

# Version
apollo-client: 0.5.25

**Comment by Axure** [comment]
And it seems already remove in 1.0.0-rc5, yet I don't know what to use for a replacement.

**Comment by stubailo** [comment]
Hey, thanks for posting here. I just updated the docs with the new syntax: https://github.com/apollographql/react-docs/commit/149c45cabb385f15aa04712a7bf72ee06445074c
