### ISSUE TITLE
Add wsClient to networkInterface to use subscriptions

### ISSUE THREAD

**Issue by pyankoff** [apollographql/react-docs#145]
Struggled with this for some time until found this: https://github.com/graphcool-examples/react-apollo-instagram-subscriptions-example/blob/da5aa6bd1493bff9f14e1df1d2f36d4baf35f74a/src/index.js

**Comment by helfer** [comment]
Thanks @pyankoff! Could you make a small PR to add a hint in the right place?

cc @Urigo we should update the transport so it no longer needs to monkey-patch the network interface, agreed?

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
