### ISSUE TITLE
Most important page need clarification and example

### ISSUE THREAD

**Issue by whitneyland** [apollographql/react-docs#159]
I would argue this is one of the most important doc pages because it's the point at which people are first trying to get their own code working:
[http://dev.apollodata.com/react/queries.html](http://dev.apollodata.com/react/queries.html)

1)  Ellipses should never be used in example code.  Its not always obvious for people learning new techs. 
`class Profile extends Component { ... }`

2)  There is no example use of ProfileWithData which is the important result.  Why not at least throw in a line to show it used on the console:
`console.log(ProfileWithData.data)`

3)  I implore you, beg you, to consider adding some CodePens with pages like this.  It would make all these other issues irrelevant.  Yes I've seen the sample project but there's many scenarios where this cannot be as effective as a self-contained pen.

Hopefully soon I'll have a clue about any of this and be able to submit a PR.

**Comment by helfer** [comment]
Thanks for the feedback @WhitneyLand. A PR would definitely be much appreciated!

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
