### ISSUE TITLE
Document how to fetch existing values from the store

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-docs#164]
Seems like a missing use case from here:

https://github.com/apollographql/react-docs/blob/master/source/optimistic-ui.md

Ex: A mutation moves an item between lists; My store knows about the item's title, but my mutation doesn't. My reducer needs to know the title to add the item to the list.

Is there a way to do this right now? I'm not sure.

**Comment by helfer** [comment]
@tmeasday do you think this is covered by the new imperative store API via the `update` function?

**Comment by tmeasday** [comment]
I think you can do it with an `update` function but I'm not sure it's at all obvious how you would do that.

**Comment by Fxlr8** [comment]
I have the same issue. My page has two lists: friends and friendship requests. Elements of those lists share the same type name, and I want to be able to move them from one list to another. I don't see any obvious way to do this using `update` method. Is there a way to manage relations in cached data? Here is the question on StackOverflow that describes the similar issue https://stackoverflow.com/questions/45282963/add-remove-item-from-apollo-cache-change-cache-data-order
