### ISSUE TITLE
static fragments webpack

### ISSUE THREAD

**Issue by obartra** [apollographql/react-docs#185]
Hey there!

I was wondering if it would make sense to document how to use static fragments in the [fragments](http://dev.apollodata.com/react/fragments.html) section as well.

I see it under the [webpack](http://dev.apollodata.com/react/webpack.html#Fragments) but it may be worth a link, something like "if you are using webpack you can also include fragments with '#import' statments. See the webpack section for details"

**Comment by stubailo** [comment]
Sure, please send a PR!
