### ISSUE TITLE
Update store after mutation. update vs updateQueries

### ISSUE THREAD

**Issue by tafelito** [apollographql/react-docs#207]
Hi,

In the docs you talk about how to update the store after a mutation. In the Usage section you mention 3 different ways of updating the store. Using refetchQueries, updateQueries or Query reducer. And the in the API reference guide, there is also update.

Is there any reason why update is not mentioned in the reference guide? Should we use update over updateQueries instead? Or the functionality is intended for different approaches?

Thanks

**Comment by helfer** [comment]
Hi @tafelito. The currently recommended approach is to use `update`, but we simply haven't had time to change the docs yet. If you have some time to make a PR to add `update` to the store update docs, that would be really great! 🙏

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
