### ISSUE TITLE
Search the docs

### ISSUE THREAD

**Issue by leoasis** [apollographql/react-docs#212]
It'd be great if the docs had a search field to quickly search for terms and go to the correct page, similar to how the [React docs](https://facebook.github.io/react/docs) work.

Since this site is implemented with Hexo, I found some plugins that could help with this functionality, like https://github.com/LouisBarranqueiro/hexo-algoliasearch. 

Is this something you'd like to receive contributions for? Has there been any previous effort on this?

**Comment by helfer** [comment]
Hey @leoasis. I agree, it would be really cool to have a search bar for our docs.

I've just submitted the url to https://community.algolia.com/docsearch/

If there's something you can help with once I hear back from them, I'll let you know! If you could help set it up, that would be an extremely valuable contribution to the community! :pray:

If you're interested in getting involved in Apollo in general, please feel free to PM me on the Apollo [slack channel](apollodata.com/#slack).

**Comment by leoasis** [comment]
Great! Awesome news. Let me know if help is needed, would like to help on this front! I'm already in the Apollo Slack, starting to get a little more active as I'm using more and more Apollo (and React Apollo) in one of my projects. Would love to get involved and help however I can!

**Comment by stubailo** [comment]
Looks like search works now! But we would still really appreciate contributions! Let me know in Slack in #contributing if you need a place to start.

**Comment by zebapy** [comment]
Where'd search go? I can't find it on apollographql.com
