### ISSUE TITLE
The doc theme has a widget where the trial has expired

### ISSUE THREAD

**Issue by brendonjohn** [apollographql/react-docs#217]
`hexo-theme-meteor` is being used as a theme. The theme includes a widget for leaving feedback and this relies on a service where the trial has expired. 

where the widget is configured: https://github.com/meteor/hexo-theme-meteor/blob/23757204d9af572cd8eb4764555405d165f6ce57/layout/layout.ejs#L37

![image](https://cloud.githubusercontent.com/assets/1642974/25602984/209d28a6-2f4c-11e7-8778-0df5a414699b.png)

I suggest moving the use of `hexo-theme-meteor` to a commit where the feedback widget was removed.

**Comment by stubailo** [comment]
Thanks, removed!
