### ISSUE TITLE
SSR instructions for request headers in network interface unclear/not accurate?

### ISSUE THREAD

**Issue by calvinl** [apollographql/react-docs#228]
Hello,

I'm using `apollo-client` on a project with server-side rendering with a GraphQL API from graph.cool, and I came across this issue. According to the docs, we need to add the request headers as options to `createNetworkInterface()` on the server, specifically documented here: https://github.com/apollographql/react-docs/blame/master/source/server-side-rendering.md#L99

Here is my setup on an Express `4.13.3` server on my localhost:

```
const client = new ApolloClient({
  ssrMode: true,
  networkInterface: createNetworkInterface({
    uri: GRAPHQL_ENDPOINT,
    opts: {
      credentials: 'same-origin',
      headers: req.headers,
    },
  }),
});
```

Passing the request headers above produces the following error when trying to access my graphcool API:

```
Error: Network error: request to https://api.graph.cool/simple/v1/[redacted] failed, reason: write EPROTO 140736015500224:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:
```

After consulting with some of the guys at graphcool, it seems that removing the `headers` option actually makes this work, and it does indeed after removing it. 

I seem to be reading documentation around the internet that suggests it needs to be there, but it doesn't work for me. Which way is correct, and does the documentation need to be updated?

**Comment by stubailo** [comment]
Hmm, looks like in `GitHunt` we don't pass through all of the headers, but instead pass the `cookie` header explicitly. Perhaps that might work better?

**Comment by calvinl** [comment]
@stubailo I'll try that. Should I submit a PR to fix the docs if it works?

**Comment by stubailo** [comment]
Yes please! I think probably passing through all of the headers is not going to be a good decision for people, so we should definitely change the docs there.

**Comment by stubailo** [comment]
This was fixed!
