### ISSUE TITLE
Chrome Wants to Kill Page On Error

### ISSUE THREAD

**Issue by zach-is-my-name** [apollographql/react-docs#230]
**Error**

```
Uncaught Error: Error: No input element in the page matches #mobile-search-input
    at Function.value (http://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js:2:3712)
    at new t (http://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js:2:2151)
    at e (http://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js:2:856)
    at http://dev.apollodata.com/react/api-queries.html:614:24
    at Array.forEach (native)
    at http://dev.apollodata.com/react/api-queries.html:613:31
```

**Comment by zach-is-my-name** [comment]
Sorry can't tell if this is Chrome or Apollo? I only experience it at  http://dev.apollodata.com/

**Comment by zach-is-my-name** [comment]
It is coming from mutations.html Line 493

<script type="text/javascript" src="//cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js"></script>

Annoying, I can't read the docs for two mins with-out needing to dismiss chrome "Wait" dialog

**Comment by stubailo** [comment]
Oh gosh! What chrome build are you running? What OS?

**Comment by zach-is-my-name** [comment]
Hey subailo, no worries. Heard you had an awesome keynote. 

Running **Chrome Version 58.0.3029.96** (64-bit) on **Ubuntu 16.10**

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
