### ISSUE TITLE
missing import ?

### ISSUE THREAD

**Issue by vgrafe** [apollographql/react-docs#237]
My code seems to work when I follow the example described [there](https://github.com/apollographql/react-docs/blob/master/source/auth.md#header), but I need to know - should `applyMiddleware` be imported from redux, or is it somehow globally accessible?

Thanks!

**Comment by stubailo** [comment]
`applyMiddleware` is a method _you_ define! The code is ES2015:

```js
// ES2015
networkInterface.use([{
  applyMiddleware(req, next) {
    // ...
  }
}]);
```

In ES5 it would be:

```js
// ES2015
networkInterface.use([{
  applyMiddleware: function (req, next) {
    // ...
  }
}]);
```

So `applyMiddleware` is just a key on an object you are passing into the `use` method.

**Comment by vgrafe** [comment]
oh wow - my bad. I should stop coding late D:
