### ISSUE TITLE
Clarify scaling issues with subscriptions

### ISSUE THREAD

**Issue by viridia** [apollographql/react-docs#254]
Reading the docs, I am really not clear on how to manage large numbers of subscriptions, especially multiple subscriptions to the same object.

Here's an example: Suppose I have a "User" query that fetches information about a user. And let's say that there are a lot of react components that display a user. For example, there's an Avatar component, a UserNameLink component, a SharingList component, a PeoplePicker component, and so on. Each of these components can occur many times on a page, and in many cases you'll have multiple components pointing to the same User object.

Now let's add subscriptions into the mix. If someone changes their avatar image or name, I'd like it to re-render the components as appropriate.

Following the examples in the docs, I would have to add a subscribeToMore() call into the graphql() wrapper for each of these components.

First, that's a lot of complex boilerplate to add to components that are otherwise rather simple.

But second, I'm concerned about what happens when I have so many subscriptions happening. If I have 5 avatars displaying the data for user Fred, does that mean that when Fred changes his profile photo I get 5 callbacks or just one?

Is there a way that I can do the subscriptions globally rather than attaching them to individual components? Ideally I would have just one subscription that is associated with the cached query in the store. Then when the cache gets updated, everything would get re-rendered.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
