### ISSUE TITLE
credentials: include - sending cookie value cross domain

### ISSUE THREAD

**Issue by rajatpandit** [apollographql/react-docs#255]
I have my project a domain ui.domain.com and graphql running on api.niamod.com. i am using passport for authentication on ui and api both, the session cookie is set on domain ui.domain.com however when i make the graphql request, with the configuration below, the cookie is not set along with the request header.

I suspect the reason being that the cookie is set in the domain .domain.com and hence can't be sent along with the header. any idea how this will work for cross domain or did the documentation intended to mean subdomain instead of domain.

`
const networkInterface = createNetworkInterface(
  'https://example.com/graphql',
  {credentials: 'include'}
);
`

**Comment by stubailo** [comment]
I don't think that's actually possible, you need to make sure to set the cookie on `*.domain.com`, otherwise the browser won't send it. That's not something we can fix in the library.

**Comment by rajatpandit** [comment]
i thought so,  perhaps worth updating the library to explicitly say its subdomain rather that different domain (that it currently says) i will be resolving this using a pass thru proxy using nginx for now, until i switch to a universal app.

**Comment by stubailo** [comment]
Thanks, can you file a PR?

**Comment by ChenLi0830** [comment]
It worked for me. I am using localhost:3000 to host client and localhost:4000/graphql to host n Graphql server. 

###Client: 
```
const networkInterface = createNetworkInterface({
  uri: uri,
  opts: {
    credentials: 'include',
  }
})
```

###Server (node-express):
```
const corsOptions = {
  origin: 'http://localhost:3000',
  credentials: true // <-- REQUIRED backend setting
};
app.use(cors(corsOptions));

app.use('/graphql', expressGraphQL({
  schema,
  graphiql: true
}))
```

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
