### ISSUE TITLE
Unsubscribing documentation

### ISSUE THREAD

**Issue by DevanB** [apollographql/react-docs#272]
I've noticed one or two individuals in the Apollo Slack who are asking about documentation on unsubscribing. 

After thinking that this type of information would be in the [Subscriptions](http://dev.apollodata.com/react/subscriptions.html) section of the Usage area, I was slightly shocked that the word "unsubscribe" doesn't appear on the page at all. 

I haven't researched into the API or used subscriptions substantially, but adding some content on unsubscribing in the docs seems helpful. :)

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
