### ISSUE TITLE
How to connect React-TS-Class with GraphQL-Wrapper?

### ISSUE THREAD

**Issue by Saifadin** [apollographql/react-docs#275]
While reading the documentation about Typescript with React and Apollo, I wanted to know how to use it with Classes. On this [page](https://github.com/apollographql/react-docs/blob/master/source/using-with-types.md#classes-vs-functions) I found the following code examples:

### Flow

```javascript
// @flow
import { ChildProps } from "react-apollo";

const withCharacter: OperationComponent<Response, InputProps> = graphql(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  })
});

// flow will infer this type 
export default class Character extends Component {
  render(){
    const { loading, hero, error } = this.props.data;
    if (loading) return <div>Loading</div>;
    if (error) return <h1>ERROR</h1>;
    return ...// actual component with data;
  }
}

const CharacterWithData = withCharacter(Character);
```

### Typescript

```javascript
import { ChildProps } from "react-apollo";

const withCharacter = graphql<Response, InputProps>(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  })
});

export default class Character extends React.Component<ChildProps<InputProps, Response>, {}> {
  render(){
    const { loading, hero, error } = this.props.data;
    if (loading) return <div>Loading</div>;
    if (error) return <h1>ERROR</h1>;
    return ...// actual component with data;
  }
}
```

Now in the last line of the Flow example `withCharacter` wraps `Character` and links them together. I don't quite understand how the Typescript Class is wrapped? Is the documentation just missing the line:

```javascript
const CharacterWithData = withCharacter(Character);
```

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
