### ISSUE TITLE
Query batching documentation

### ISSUE THREAD

**Issue by DevanB** [apollographql/react-docs#276]
While lurking in the Graphcool and Apollo Slack teams, I've noticed a recurring topic of query batching being asked about and discussed. 

Seems like it would be a good page to add in the Recipes section of the docs.

**Comment by stubailo** [comment]
We've got some docs here: http://dev.apollodata.com/core/network.html#query-batching

Would be great to add a recipe on the React page as well!

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
