### ISSUE TITLE
Create a subscription without a query?

### ISSUE THREAD

**Issue by Fxlr8** [apollographql/react-docs#285]
Hi, [here](http://dev.apollodata.com/react/receiving-updates.html#Subscriptions) and [here](http://dev.apollodata.com/react/subscriptions.html#subscribe-to-more) the only option to use the subscription is to use it as a prop after you wrap your component with a graphql query HOC. But I just desperately tried this:
```
@graphql(NEW_MESSAGE_SUBSCRIPTION, {
	props: ({ data: { newMessage } }) => ({
		newMessage
	})
})
class BlahBlah extends...
```
and it surprisingly worked! Every time I get a new message my `newMessage` prop updates. This is good, but what if I want an `update` called every time I get a new message to update the store. **I don't want to use query here, only the subscription**. I have a page with a list of dialogs. Each of them has the last message from that dialog displayed. I think this is an overkill to subscribe for every dialog in a list after querying it. So I want to create a single subscription and then use an `update` method to update my store. How can I do it? One more reason to only use the subscription is that I want to make it somewhere close to the app root, not only at the dialogs page, to be able to display notifications on new messages.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
