### ISSUE TITLE
"Connecting Data" Section of 'Setup and options' Could Be More Explicit

### ISSUE THREAD

**Issue by johndanek** [apollographql/react-docs#288]
http://dev.apollodata.com/react/initialization.html#connecting-data

The first example in this section is great; it clearly states all the variables necessary to get an example working.

The second example is not as explicit and assumes that the reader is aware of what is missing. This may cause beginners some difficulty.

**Comment by stubailo** [comment]
@johndanek wow, awesome suggestion, would love to see a PR for this!

**Comment by johndanek** [comment]
@stubailo If I can get my app to work, I'll gladly add it. But I'm not there yet ;-)

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
