### ISSUE TITLE
Docs need to include new graphql() "client" option

### ISSUE THREAD

**Issue by estaub** [apollographql/react-docs#294]
A feature was added to allow use of multiple Apollo clients.

See https://github.com/apollographql/react-apollo/pull/729, released a couple of months ago.

Quoting from that:

```
graphql(query, {
  options: props => ({ client: ... }),
})(MyComponent)

```

where I assume `client` is an ApolloClient.  I haven't used it yet, or I'd float a doc PR myself.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
