### ISSUE TITLE
Missing: API Reference > ApolloClient constructor

### ISSUE THREAD

**Issue by lorensr** [apollographql/react-docs#307]
https://www.apollographql.com/docs/react/reference/index.html#ApolloClient\.constructor

![image](https://user-images.githubusercontent.com/251288/32411028-d661437e-c1a6-11e7-8888-466e155aad7e.png)

It is, however, found elsewhere:

https://www.apollographql.com/docs/react/basics/setup.html#ApolloClient

![image](https://user-images.githubusercontent.com/251288/32411031-e9b015c2-c1a6-11e7-88f7-0b894e3fe132.png)

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
