### ISSUE TITLE
Relative link to favicon does not work on pages deeper in the tree

### ISSUE THREAD

**Issue by iki** [apollographql/react-docs#309]
[Main page](https://www.apollographql.com/docs/react/) relative link to [images/favicon.png](https://www.apollographql.com/docs/react/images/favicon.png) works ok, but it can't and doesn't work for pages deeper in the tree, e.g. [queries](https://www.apollographql.com/docs/react/basics/queries.html).

**Comment by stubailo** [comment]
Hi, thanks for the issue - the docs have been moved to the same repository as the code for 2.x. I think we've fixed a lot of the issues, but please file any new ones there!

New repo: https://github.com/apollographql/apollo-client
New live site: https://www.apollographql.com/docs/react/

**Comment by stubailo** [comment]
Sorry, I see this is still relevant

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
