### ISSUE TITLE
Add documentation for `forceFetch`

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-docs#44]
OK, I now realise I don't properly understand how `forceFetch` works.

**Comment by stubailo** [comment]
`forceFetch` makes it so that your queries always hit the network. By default, if the result is in the cache, you don't send a request at all. `forceFetch` disables that behavior.

**Comment by tmeasday** [comment]
Oh, sorry if I was unclear. I understand that `query({ forceFetch })`. However, based on conversations that we had earlier around the React implementation (it should force fetch the query the first time the component is rendered, and not afterwards) I was surprised to see that that is not how `graphql(..., { options: { forceFetch: true })` works.

**Comment by stubailo** [comment]
oh, that's a good point. I guess it fetches every time?

**Comment by tmeasday** [comment]
Yes, and if you turn `forceFetch` off it possibly never fetches (this is based on reading the source, I want to confirm that behaviour).

I'm not sure if we want to change this, but it renders part of the refactoring project moot if we don't have this feature. We should discuss this a little.

**Comment by stubailo** [comment]
I think we might want to change this. Maybe not in this specific way, but I'm 100% sure we need something in between "never fetch" and "always fetch every single time"

Ideally, it would be a cache expiration thing, but that might be a "big" feature.
