### ISSUE TITLE
Api Reference for React Apollo

### ISSUE THREAD

**Issue by lpalmes** [apollographql/react-docs#64]
It could be nice to have an api reference for high order components and such, given that from the examples i seem to get lost.

Like from this example, i had to console log the arguments of props function to see that it returns mutate and ownProps too. Maybe a bit of Api reference would come in handy.

```
import React, { Component, PropTypes } from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

class NewEntry extends Component {
  render() {
    return <div onClick={this.props.submit('apollostack/apollo-client')}>Click me</div>;
  }
}
NewEntry.propTypes = {
  submit: PropTypes.func.isRequired,
};

const submitRepository = /* as above */;

const NewEntryWithData = graphql(submitRepository, {
  props: ({ mutate }) => ({
    submit: (repoFullName) => mutate({ variables: { repoFullName } }),
  }),
})(NewEntry);
```

Great work over here,
Thanks!

**Comment by helfer** [comment]
Agreed, this is something we want to improve soon.

**Comment by lpalmes** [comment]
@helfer if you need help from someone who is unfamiliar to the library let me know, i would be happy to help

**Comment by stubailo** [comment]
This exists now! http://dev.apollodata.com/react/api.html
