### ISSUE TITLE
Co-location of components and queries

### ISSUE THREAD

**Issue by tslocke** [apollographql/react-docs#69]
[These](https://github.com/apollostack/react-docs/blob/master/source/index.md#comparison-with-other-graphql-clients) remarks, in the Apollo/React docs, mention "[Relay] focuses on enabling the co-location of queries and components".

This seems to imply Apollo Client is a little weaker in that regard.

However, GraphQL queries are trivially composable. What's stopping me from writing static query methods on my React components? It seems like this is a fundamental strength of GraphQL itself, not the particular client library.

Am I missing something?

Thanks

**Comment by helfer** [comment]
@tmeasday has recently built a package for apollo-client that lets you declare a component's data requirements with fragments, just as Relay does. See https://github.com/apollostack/GitHunt-React/pull/112

**Comment by tmeasday** [comment]
Working on docs at the moment.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
