### ISSUE TITLE
using props field in the graphql function

### ISSUE THREAD

**Issue by derekdreery** [apollographql/react-docs#98]
When I came to apollo with react, I was used to redux, and writing my presentational components to be independent of my actions - then using `connect` to map redux to my presentational props.

The equivalent in apollo is to use the `props` field in the second argument to `graphql` function. I didn't understand this from the documentation, (eventually I understood it from http://dev.apollodata.com/react/cache-updates.html), so I naively created new react components to map `data` and `mutate` to my methods.

IMO using `props` is the best way to use the `graphql` function (separates presentation logic), so my questions are:
 - Is my view the consensus view?
 - If so, should this be stressed in the documentation, with an example, on the page for queries or mutations?
 - Have I just been blind and that documentation is already there? :)

**Comment by helfer** [comment]
@jbaxleyiii @tmeasday curious to hear your thoughts on this. I think we should structure our docs in such a way that they make sense to people who are already familiar with React best practices.

**Comment by tmeasday** [comment]
@derekdreery, it is documented here: http://dev.apollodata.com/react/queries.html#graphql-props ("Using `props`"). I wonder how we could give it more prominence?

Although I personally agree with it, (and wrote the line "This style of usage leads to the greatest decoupling between your presentational component (Profile) and Apollo" I think it is *not* a consensus view at this point.

I think ultimately it comes down to how view driven your schema is. If your schema is driven by the data requirements of your UI hierarchy, then your component props pretty much map 1-1 to the structure of your query results. In that case, it doesn't necessarily justify the effort of using `props` all over the place.

However, I personally think given
 a) component reuse is good
 b) you eventually may have more than one UI
 c) your schema shouldn't be driven by the UI, IMO

That it's better to use `props`. 

Obviously it's a nice shortcut to just use `data` also.

**Comment by derekdreery** [comment]
@tmeasday thanks for the response. The questions I had in my head when I raised this ticket were "why did I misunderstand the documentation", "is it something other people might do as well", and "is there a way to make it less likely". It may be that the answer to 2 or 3 is "no",  but I thought bringing it up add something to the discussion.

When I read documentation, I tend to do it 'lazily', in that I look for the minimum amount of information that allows me to carry on working, and then come back when I need some more information. I think this is a sensible way to work, as you get information overload if you try to read every line of docs at once, but it does have the disadvantage that you might miss important information.

For people who read documentation like this, it is beneficial to have key information about design decisions feature prominently, followed by technical information, as you need to make design decisions at the beginning.

Applying that principal to this situation would be adding something like

> NOTE: If you have existing components, or want to separate presentational components from data, see `link to props section`. 

This would be ignored by anyone new to react, but would immediately be noticed by those familiar to redux and wanting to follow the same pattern as `connect`.

I hope this is useful to you. I'm really just trying to give some feedback as a new user who doesn't understand the apollo structure fully yet.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

And are live at apollographq.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
